### ISSUE TITLE
Editing points on gradient not working

### ISSUE THREAD

**Issue by melissafzhang** [undind/react-gcolor-picker#14]
Thanks for building this library! I'm having this bug where when trying to select the gradient color to edit (on the bottom bar),  I get the error `Cannot read property 'y' of undefined`. I upgraded to version 1.2.0 but still seeing the issue

![Screen Shot 2021-07-15 at 7 24 25 PM](https://user-images.githubusercontent.com/38673112/125882150-79fb8b28-153a-4680-bc76-083d7564022f.png)

**Comment by undind** [comment]
@melissafzhang Thanks! I fixed this bug in version 1.2.1. Please update! If something is wrong, write a new issue.
