### ISSUE TITLE
[Feature-Request]: more options via props

### ISSUE THREAD

**Issue by YeonV** [undind/react-gcolor-picker#16]
# Thank you soo much for this project!!

### Would it be possible to add some props:

- showGradientResult
- showGradientMode
- showGradientAngle
- showGradientPos
- showInputs
- showGradientResultFirst

so it would look like this:
![image](https://user-images.githubusercontent.com/28861537/143577879-8335f23a-65c2-40f6-9852-cc262466fd52.png)

### Note
Maybe the current active marker can be indicated/highlighted stronger

**Comment by YeonV** [comment]
@undind Your picker is also nice in Dark Mode:

![image](https://user-images.githubusercontent.com/28861537/144465612-182b20a0-ce54-441f-9050-57954d2d9228.png)
I just did it with dirty CSS:
https://github.com/YeonV/LedFx-Frontend-v2/blob/main/src/components/SchemaForm/BladeGradientPicker.jsx#L18-L44

**Comment by undind** [comment]
See updates in version [1.2.2](https://github.com/undind/react-gcolor-picker/compare/1.2.1...1.2.2)
