### ISSUE TITLE
Remove the gradients points

### ISSUE THREAD

**Issue by Vaal15** [undind/react-gcolor-picker#20]
Hi ! First, thansk for the awesome job !

We'd like to know if you're thinking about simplifying the deletion of gradients layers ?

I read the previous Issue about the deletion, and I found out that to remove a dot, I'd have to drag & drop it outside of the box.
But this isn't realy user friendly... are you thinking about putting an event listener on the delete key just like there https://arthay.github.io/react-color-gradient-picker/ ?

**Comment by undind** [comment]
@Vaal15 Thanks! Added in [Release 1.2.4](https://github.com/undind/react-gcolor-picker/compare/1.2.3...1.2.4)

**Comment by jasperlafortune** [comment]
Hi! We're also really liking this component. We actually didn't know about the ability to double click to remove a color stop until reading this issue. Would you consider adding a right-click context menu to remove a color stop?
