### ISSUE TITLE
Greay border on a white default color

### ISSUE THREAD

**Issue by Vaal15** [undind/react-gcolor-picker#24]
Hi ! 

We love what you did with the colorPicker but we spotted a little improvement :

When we set up a white default color, the lack of border seems like a empty space and is not well comprehended by everyone.

Could you add a grey border if the default color is white or something like that ?

<img width="266" alt="image" src="https://user-images.githubusercontent.com/90181570/169556429-81383b02-4b43-4125-bf21-b0f1caf61610.png">

Thanks for the hard work

**Comment by undind** [comment]
@Vaal15 update in version [1.3.3](https://github.com/undind/react-gcolor-picker/releases/tag/1.3.3)
