### ISSUE TITLE
Value not updating with value passed as a prop being changed to the Picker Component

### ISSUE THREAD

**Issue by SakshamPyxis** [undind/react-gcolor-picker#6]
So basically if i update the value which is being passed to the picker i dont actually update the color in the color pallete because we are not updating the state we are just initially assigning it and changing it on onChange method but not when the prop value is updated

Raising an issue just to check if the creator is active ... if yes then will fix.
Hoping a quick reply as i am using this package .. and want this functionality to be fixed as soon as possible 

![image](https://user-images.githubusercontent.com/67255326/109847442-31981380-7c75-11eb-88d5-f319a59474ec.png)

**Comment by undind** [comment]
@SakshamPyxis I'm active. When there is a fix - I will update the package or fix it myself soon

**Comment by SakshamPyxis** [comment]
@undind thanks for replying quick .. do you want me to raise a pr for this .. i wanted to use this functionality in my product by tomorrow? or you can take care of this by tomorrow if possible?

**Comment by undind** [comment]
@SakshamPyxis I'll take care of it tomorrow and leave a comment

**Comment by undind** [comment]
@SakshamPyxis Fix this problem and update package

**Comment by SakshamPyxis** [comment]
@undind Thank you soo much .. just checked seems to be working fine!
i am aware of few more issues will create issue of them also maybe try and fix them too.
