### ISSUE TITLE
No Functionality to remove a color stop

### ISSUE THREAD

**Issue by SakshamPyxis** [undind/react-gcolor-picker#7]
I didn't find any functionality to remove a color stop tried double clicking on the color stops and dragging them down 
![image](https://user-images.githubusercontent.com/67255326/109853278-be45d000-7c7b-11eb-8292-0c58e33b820f.png)

**Comment by undind** [comment]
@SakshamPyxis I apologize for the lack of this feature. I will add this functionality soon.

**Comment by undind** [comment]
@SakshamPyxis Update package with functionality to remove a color stops when dragging them down
